# Coolify Configuration for PCR Project Tracker
# This file helps Coolify understand how to deploy your application

version: '1.0'

services:
  pcr-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_APP_NAME=PCR Project Tracker
      - VITE_APP_VERSION=0.9.02
      - VITE_USE_SERVER_DB=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - /app/data:/app/data

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pcr_tracker
      - POSTGRES_USER=pcr_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

# Build configuration
build:
  buildCommand: "npm ci && npm run build"
  outputDirectory: "dist"
  nodeVersion: "18"

# Health check configuration  
healthCheck:
  path: "/"
  port: 4173
  
# Environment variables template
envTemplate: |
  # Application Settings
  NODE_ENV=production
  VITE_APP_NAME=PCR Project Tracker
  VITE_APP_VERSION=0.9.02
  
  # Database Configuration
  VITE_USE_SERVER_DB=true
  POSTGRES_DB=pcr_tracker
  POSTGRES_USER=pcr_user
  POSTGRES_PASSWORD=__GENERATE_RANDOM__
  POSTGRES_HOST=postgres
  POSTGRES_PORT=5432
  
  # Supabase (alternative to PostgreSQL)
  # VITE_SUPABASE_URL=https://your-project.supabase.co
  # VITE_SUPABASE_ANON_KEY=your-anon-key-here
  
  # Security
  JWT_SECRET=__GENERATE_RANDOM__
  SESSION_SECRET=__GENERATE_RANDOM__
  
  # Redis
  REDIS_PASSWORD=__GENERATE_RANDOM__
  
  # Email (Optional)
  # SMTP_HOST=smtp.gmail.com
  # SMTP_PORT=587
  # SMTP_USERNAME=your-email@gmail.com
  # SMTP_PASSWORD=your-app-password
  # SMTP_FROM=noreply@yourdomain.com
